images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('',views.image_list,name='list'),
    path('create/',views.image_create,name='create'),
    path('like/',views.image_like,name='like'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail,name="detail"),
    path('ranking/',views.image_ranking,name='create'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('about/',views.about,name='about'),
    path('accounts/',include('accounts.urls')),
    path('images/',include('images.urls')),
    path('',include('django.contrib.auth.urls')),
    path('oauth/',include('social_django.urls',namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

class Image(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='images_created')
    title       = models.CharField(max_length=255)
    slug        = models.SlugField(max_length=255,blank=True)
    url         = models.URLField()
    image       = models.ImageField(upload_to='images/%Y/%m/%d/')
    desc        = models.TextField(blank=True)
    created     = models.DateTimeField(auto_now_add=True,db_index=True)

    users_like  = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='images_liked',blank=True)

    total_likes = models.PositiveIntegerField(db_index=True,default=0)

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Image,self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('images:detail',kwargs={'id':self.pk,'slug':self.slug})

images/forms.py
from django import forms
from urllib.request import urlopen,Request
from django.core.files.base import ContentFile
from .models import Image
from django.utils.text import slugify

class ImageCreatForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title','url','desc')
        widgets = {
            'url':forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data.get('url')
        valid_extensions = ['jpg','jpeg']
        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("You must provide only '.jpg' or '.jpeg' extensions")
        return url

    def save(self,commit=True,*args,**kwargs):
        image = super(ImageCreatForm,self).save(commit=False)
        image_url = self.cleaned_data.get('url')
        image_name = '{}.{}'.format(slugify(image.title),image_url.rsplit('.',1)[1].lower())

        req = Request(image_url,headers={'User-Agent':'Mozilla/5.0'})
        response = urlopen(req).read()
        image.image.save(image_name,ContentFile(response),save=False)

        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ImageCreatForm
from django.contrib import messages
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from common.decorators import ajax_required

from django.views.decorators.http import require_POST
from django.http import JsonResponse,HttpResponse

from actions.utils import create_action

from .models import Image

import redis
from django.conf import settings
r = redis.StrictRedis(host=settings.REDIS_HOST,port=settings.REDIS_PORT,db=settings.REDIS_DB)

# Create your views here.

@login_required
def image_list(request):
    images = Image.objects.order_by('-created')
    paginator = Paginator(images,2)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        images = paginator.page(paginator.num_pages)
        if request.is_ajax():
            return HttpResponse('')
    if request.is_ajax():
        return render(request,'images/image_ajax_list.html',{'section':'images','images':images})
    return render(request,'images/image_list.html',{'section':'images','images':images})




@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreatForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request,"Image has Been shared Here!")
            create_action(request.user,'bookmarked image',new_item)
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreatForm(data=request.GET)
    return render(request,'images/image_form.html',{'form':form})


def image_detail(req,id,slug):
    image = get_object_or_404(Image,id=id,slug=slug)
    total_views = r.incr('image:{}:views'.format(image.id))
    r.zincrby('image_ranking',1,image_id)
    # print(r.zincrby('image_ranking',1,image.id)) zincrby(key,amount,value)
    return render(req,"images/image_detail.html",{'image':image,'total_views':total_views})

@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking',0,-1,desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    #get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,'images/image_ranking.html',{'most_viewed':most_viewed})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                # print("adding")
                image.users_like.add(request.user)
                create_action(request.user,'liked',image)
            else:
                # print("removing")
                image.users_like.remove(request.user)
                create_action(request.user,'unliked',image)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

images/templates/images/image_ajax_list.html
{% load thumbnail %}
<div class="container">
    <div class="row">
      {% for image in images %}
          <div class="col">
            <a href="{{ img.get_absolute_url }}">
                {% thumbnail image.image "300x300" crop="100%" as im %}
                  <a href="{{ image.get_absolute_url }}">
                      <img src="{{im.url}}" alt="{{im.title}}" title="{{im.title}}">
                  </a>
                {% endthumbnail %}
            </a>
            <div class="my-1">
              <h4><a href="{{image.get_absolute_url}}">{{image.title}}</a></h4>
            </div>
        </div>
    {% endfor %}
  </div>

</div>

images/templates/images/image_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% block title %} Add Image {% endblock%}
{% block content %}
  <div class="jumbotron m-0" style="background-color: #08091F;color: #DAE0F2; border-radius: 0;">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          {% thumbnail image.image "400" as im %}
            <a href="{{ image.image.url }}">
              <img
                  class="img-detail"
                  src="{{ im.url}}"
                  alt="{{ image.title|truncatewords:5}}"
                  title="{{ image.title|truncatewords:5}}"
              >
            </a>
          {% endthumbnail %}

        </div>
        <div class="col-lg-7">
          <div class="text-center">
            <h3 class="display-4 text-uppercase text-success">{{image.title}}</h3>
          </div>
          {% with total_likes=image.users_like.count users_like=image.users_like.all %}
          <p>
            {% for u in users_like %}
              <img src="{{u.profile.image.url }}" title="{{u.username}}" style="border-radius:50%;width:50px;height:50px;object-fit:cover;">
              {% empty %}
              No one has liked it yet!
            {% endfor %}
          </p>

          <div class="d-flex justify-content-between">
            <span class="total">
              <span class="count">{{total_likes}}</span> Like{{total_likes|pluralize}}
              <span class="ml-4">{{total_views}} view{{total_views|pluralize}}</span>
            </span>
            <a href="#" data-id="{{	image.id	}}"
            data-action="{%	if request.user	in users_like	%}un{% endif %}like" class="like btn btn-outline-success">
              {%	if	request.user	not	in	users_like	%}
                Like
              {%	else %}
                Unlike
              {% endif %}
            </a>
          </div>

          {% endwith %}

          <div class="text-center border-left my-4 px-5">
            {{image.desc|linebreaks }}
          </div>
          <div class="author text-success font-weight-bold m-4 pt-4">
            <p class="float-left">Published On - {{image.created|date}}</p>
            <p class="float-right">~ {{image.user}}</p>
            <div class="clearfix"></div>
          </div>
        </div>

      </div>
      </div>
  </div>
{% endblock %}



<script>

  {% block domready %}
    $('a.like').click(function(e){
      e.preventDefault();
      $.post('{% url "images:like" %}',
        {
          id: $(this).data('id'),
          action: $(this).data('action')
        },
        function(data){
          if(data['status']=='ok')
          {
            let previous_action = $('a.like').data('action');
            $('a.like').data('action',previous_action == 'like' ? 'unlike' : 'like');
            $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

            let previous_likes = parseInt($('span.total .count').text());
            $('span.total .count').text(previous_action=='like'?previous_likes + 1:previous_likes - 1)
          }
        }
      );
    });
  {% endblock domready %}

  </script>

images/templates/images/image_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add Image {% endblock%}
{% block content %}
  <div class="jumbotron">
    <div class="container">
      <form class="d-flex justify-content-around" method="post">
        {% csrf_token %}
        <img src="{{ request.GET.url }}" alt="image-preview" style="width: 600px;height:500px;object-fit:cover;">
        <fieldset>
          <legend>Bookmark an Image</legend>
          {{ form|crispy }}
          <input type="submit" class="btn btn-outline-success btn-lg" value="Bookmark it!">
        </fieldset>
      </form>

    </div>
  </div>
{% endblock %}

images/templates/images/image_list.html
{% extends 'base.html' %}
{% block title %} Images Bookmarked {% endblock%}
{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h2 class="display-2">Images Bookmarked</h2>
      <div id="image-list">
        {% include 'images/image_ajax_list.html' %}
      </div>
    </div>
  </div>
{% endblock %}
<script>
  {% block domready %}
    let page = 1;
    let empty_page = false;
    let block_request = false;

    $(window).scroll(function(){
      var margin = $(document).height() - $(window).height() - 200;
      if($(window).scrollTop() > margin && empty_page == false && block_request == false){
        block_request = true;
        page += 1;
        $.get('?page='+page,function(data){
          if(data == ''){
            empty_page = true;
          }else{
            block_request = false;
            $('#image-list').append(data);
          }
        })
      }
    });

  {% endblock domready %}
</script>

images/templates/images/image_ranking.html
{% extends 'base.html' %}
{% block title %} Images Ranking {% endblock %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">Image Ranking</h2>
    <hr>
    <ol class="mt-3">
      {% for i in most_viewed %}
      <li><a href="{{i.get_absolute_url}}" class="text-success font-weight-bold">{{i.title}}</a></li>
      {% endfor %}
    </ol>
  </div>

</div>
{% endblock %}