images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('',views.image_list,name='list'),
    path('create/',views.image_create,name='create'),
    path('like/',views.image_like,name='like'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail,name="detail"),
    path('ranking/',views.image_ranking,name='create'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('about/',views.about,name='about'),
    path('accounts/',include('accounts.urls')),
    path('images/',include('images.urls')),
    path('',include('django.contrib.auth.urls')),
    path('oauth/',include('social_django.urls',namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nature{% endblock %}
{% block content %}
	<div class="jumbotron jumbotron-fluid height100v">
		<div class="container h100">
			<div class="headerText">
				<h1 class="display-1">About Page</h1>
				<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
				<hr class="my-4">
				<a href="#" class="btn btn-outline-primary btn-lg">Blog</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  {% include 'head.html' %}
  <body>
    <header>
    	{% include 'navbar.html'%}

    	{% if messages %}
	    	<div class="container-fluid m-0 p-0">
	    		{% for msg in messages %}
		    		<div class="alert alert-{{ msg.tags }} m-0">
		    			{{ msg }}
		    		</div>
		    	{% endfor %}
	    	</div>
   		{% endif %}
    </header>

    <main>
    	{% block content %}
    	{% endblock %}
    </main>

    <footer></footer>

    {% include 'scripts.html' %}
    <script>
      var	csrftoken	=	Cookies.get('csrftoken');
      function	csrfSafeMethod(method){
        //	these	HTTP	methods	do	not	require	CSRF	protection
        return	(/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
        	beforeSend:	function(xhr,	settings){
            	if	(!csrfSafeMethod(settings.type)	&&	!this.crossDomain){
                		xhr.setRequestHeader("X-CSRFToken",	csrftoken);
                  }
                }
            });
    	$(document).ready(function(){
        {% block domready	%}
        {% endblock domready %}
      });
    </script>
  </body>
</html>

templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block styles %}
    {% endblock %}
    <title>{% block title %}Instagramy{% endblock %}</title>
</head>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nature{% endblock %}
{% block content %}
	<div class="jumbotron jumbotron-fluid height100v">
		<div class="container h100">
			<div class="headerText">
				<h1 class="display-1">Instagramy</h1>
				<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
				<hr class="my-4">
				<a href="#" class="btn btn-outline-primary btn-lg">Blog</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Nature</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Blog</a>
      </li>
    </ul>
    <ul class="navbar-nav mx-lg-auto">
      {% if user.is_authenticated %}
        <li class="nav-item {% if section == 'dashboard' %}active{% endif %}">
          <a class="nav-link" href="{% url 'dashboard' %}">Howdy,{{ request.user }}</a>
        </li>
        <li class="nav-item {% if section == 'images' %}active{% endif %}">
          <a class="nav-link" href="{% url 'images:list' %}">Images</a>
        </li>
        <li class="nav-item {% if section == 'people' %}active{% endif %}">
          <a class="nav-link" href="{% url 'users_list' %}">People</a>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav ml-lg-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
      {% endif %}

    </ul>
 </div>
</nav>

templates/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>